# Generated by Django 2.0.2 on 2019-07-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='feature_voted',
            field=models.ForeignKey(on_delete='CASCADE', to='features.FeaturePost'),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='order',
            field=models.ForeignKey(on_delete='CASCADE', to='checkout.Order'),
        ),
    ]
