# Generated by Django 2.0.2 on 2019-07-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurecomment',
            name='post',
            field=models.ForeignKey(on_delete='CASCADE', related_name='bugs', to='features.FeaturePost'),
        ),
    ]
