# Generated by Django 2.0.2 on 2019-07-04 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_auto_20190704_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurecomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to='features.FeaturePost'),
        ),
    ]
