# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-20 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='votes_cost',
            field=models.IntegerField(default=0),
        ),
    ]
