# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-23 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0005_post_votes_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
    ]
