# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-28 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0008_auto_20190525_1106'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='FeatureComment',
        ),
        migrations.RenameModel(
            old_name='Post',
            new_name='FeaturePost',
        ),
    ]
