# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-30 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0009_auto_20190528_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurepost',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
    ]
