# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-19 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugpost',
            name='big',
        ),
        migrations.AlterField(
            model_name='bugpost',
            name='start_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
