# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-19 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_auto_20190619_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugpost',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bugpost',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
