# Generated by Django 2.0.2 on 2019-07-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0003_auto_20190619_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugcomment',
            name='post',
            field=models.ForeignKey(on_delete='CASCADE', related_name='bugs', to='bugs.BugPost'),
        ),
    ]
