# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-30 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0007_auto_20190528_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugpost',
            name='status',
            field=models.CharField(choices=[('To Do', 'To Do'), ('Doing', 'Doing'), ('Done', 'Done')], default='To Do', max_length=50),
        ),
    ]
