# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-30 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0008_bugpost_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugpost',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
    ]
